server:
  port: 7001

eureka:
  instance:
    hostname: eureka-cluster-one
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: ${eureka.client.register-with-eureka} #false表示自己端就是注册中心,我的职责就是维护服务实例,并不需要检索服务
    service-url:
      # 单机: http://${eureka.instance.hostname}:${server.port}
      #集群:  http://eureka-cluster-two:7002/eureka
      defaultZone: http://eureka-cluster-two:7002/eureka
  server:
    enable-self-preservation: ${eureka.client.register-with-eureka} #关闭自我保护模式，保证不可用服务被及时删除
    eviction-interval-timer-in-ms: 5000 #多少秒剔除不可用服务