server:
  port: 9527

spring:
  application:
    name: @project.artifactId@
  cloud:
    gateway:
      routes:
        - id: route_ok #路由id，没有规定规则但要求唯一，建议配合服务名
          uri: http://localhost:80 #匹配后提供服务的路由地址
          predicates:
            - Path=/consumer/order_hystrix/ok #断言，路径相匹配的进行路由

        - id: route_time_out
          uri: http://localhost:80
          predicates:
            - Path=/consumer/order_hystrix/time_out

        - id: route_circuit_breaker
          uri: http://localhost:80
          predicates:
            - Path=/consumer/order_hystrix/circuit_breaker/**

        #            - After=2020-12-08T13:41:21.177+08:00[Asia/Shanghai] #设置在什么时间后可访问
        #            - Before=2020-12-09T13:41:21.177+08:00[Asia/Shanghai] #设置在什么时间前可访问
        #            - Between=2020-12-08T13:41:21.177+08:00[Asia/Shanghai],2020-12-09T13:41:21.177+08:00[Asia/Shanghai] #设置在什么时间之内可访问
        #            - Cookie=username,sh

eureka:
  client:
    service-url:
      defaultZone: http://eureka-cluster-one:7001/eureka,http://eureka-cluster-two:7002/eureka
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: ${eureka.instance.lease-renewal-interval-in-seconds}