server:
  port: 80

spring:
  application:
    name: cloud-consumer-order-feign-service
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-cluster-one:7001/eureka,http://eureka-cluster-two:7002/eureka
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: ${eureka.instance.lease-renewal-interval-in-seconds}

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: ${ribbon.ReadTimeout}

logging:
  level:
    com.sh.consumer.order.service: debug