server:
  port: 3344

spring:
  application:
    name: @project.artifactId@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shtns/cloud-config-detail.git
          username: shtns
          password: sh20000907
          search-paths:
            - cloud-config-detail
      label: master
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: ${spring.rabbitmq.username}

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #集群版: http://eureka-cluster-one:7001/eureka,http://eeureka-cluster-two:7002/eureka
      #单机版: http://1eureka-cluster-one:7001/eureka
      defaultZone: http://eureka-cluster-one:7001/eureka,http://eureka-cluster-two:7002/eureka
  instance:
    instance-id: ${spring.application.name}-${server.port} #设置Eureka Status名称
    prefer-ip-address: true #访问路径可以显示ip
    lease-renewal-interval-in-seconds: 2 #eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    lease-expiration-duration-in-seconds: ${eureka.instance.lease-renewal-interval-in-seconds} #eureka服务端收到最后一次心跳后等待时间上线，单位为秒（默认为90秒） 超时将剔除服务

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

#localhost:3344/master/application-test.yml
#curl -X POST "http://127.0.0.1:3344/actuator/bus-refresh"
#curl -X POST "http://127.0.0.1:3344/actuator/bus-refresh/cloud-config-client:3355"